### ISSUE TITLE
Bump accessory configuration version on char. changes.

### ISSUE THREAD

**Issue by gerswin** [ikalchev/HAP-python#13]
it's me again, can u tell me how to use name characteristic?? 

self.get_service("Lightbulb").get_characteristic("Name").set_value("Bed")

it's not working

**Comment by ikalchev** [comment]
I looked into that, here is what I found:

You can set the name characteristic, but this has to happen before you pair with iOS:
```python
# This must happen before pairing:
acc = Accessory.create("MyAcc", pincode=b"203-23-999")
s = loader.get_serv_loader().get("TemperatureSensor")
s.add_opt_characteristic(loader.get_char_loader().get("Name"))
acc.add_service(s)
s.get_characteristic("Name").set_value("Foo", False)
# OK, the service will show as Foo when paired
```

However, changing the name after that doesn't work and this is a bug in HAP-python. This is because iOS doesn't know it has new values to read. The way to notify about this, is to change the [config version](pyhap/accessory.py#L121) of the accessory - something I have not implemented yet.

Fortunately, this is not hard to fix and will do so in a few days. Until then, you can workaround this by doing:
```python
# acc is your Accessory.
# driver is the AccessoryDriver that manages acc (as in main.py)
# Change name
acc.get_service("TemperatureSensor").get_characteristic("Name").set_value("new name", False)
# Bump config version
acc.config_version += 1
# Update mDNS information so that iOS clients know they have to re-fetch acc info.
driver.update_advertisment()
# Persist the new config_version (see issue #11)
driver.persist()
```

Thanks for uncovering this, I will try to make it easier to change such optional chars (i.e. without the workaround). Note that for some optional characteristics, like StatusLowBatter, iOS listens for updates, so the workaround is not needed.

**Comment by ikalchev** [comment]
Okay update:

iOS is getting the updates every time you do 
```python
acc.config_version += 1
driver.update_advertisment()
```
However, although the value is sent to iOS it does not bother to update the UI (I have checked this by updating the config version very 3 seconds and changing the name. Every time I print the update that is sent to iOS and it contains the new name.)

I have no idea why iOS does not refresh the UI. It should happen eventually though.

**Comment by ikalchev** [comment]
Change is in. When you make a configuration change, such as adding a Service or changing a characteristic such as Name, you can call:
```python
accessory.config_changed()
```
This notifies iOS clients they need to refetch the whole accessory again and persists the new state of the accessory. Note that although iOS immediately fetches the new config, it does not update the UI immediately. However, the updates are eventually shown.
