### ISSUE TITLE
HAP-Python in MicroPython

### ISSUE THREAD

**Issue by Sunrise17** [ikalchev/HAP-python#136]
@ikalchev , how can i apply an accessory code, on ESP32 board? 
Micropython is already installed on my board. Is it possible to use HAP-Python accessories on Micropython?

**Comment by ikalchev** [comment]
What do you mean by accessory code?

I haven't tried using HAP-python on ESP32, but I have a few of them lying around. I will be happy to help you try it out if you want to. One possible issue I can think of is that the crypto libraries have C backends - I don't know if these will compile out of the box for ESP32. I have managed to port wolfssl and libpbc to ESP32 so it might work. 

Let me know if you need some info.

**Comment by bwicks** [comment]
I've been looking at this myself but with ESP8266, were you ever able to get it to work?

**Comment by ikalchev** [comment]
I haven't tried this. I know there is a HAP-python server for ESP8266 written in C (google it, I can't seem to find it now). If I remember correctly, pairing took around 2 minutes, because of the specs of ESP8266.

If someone wants to have a shot at this I will be happy to help. But I won't be able to drive this in the near future (as much as I would like to!)

Please keep the discussion going, I am closing this as a no-issue.

**Comment by Rjayone** [comment]
@ikalchev, its will be a great job, if you could to spent some time to try port this lib on esp8266 with micropython🙏🏻
I have started to do this, but faced with some errors:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "boot.py", line 26, in hap
  File "pyhap/accessory.py", line 363, in to_HAP`
