### ISSUE TITLE
Accessory calculates AID incorrectly

### ISSUE THREAD

**Issue by tagdara** [ikalchev/HAP-python#20]
The Accessory module calculates AID like this:

acc.aid = len(self.accessories) + 2

However if you have previously deleted and created a new AID, the max number of that AID is higher, so it should be:

if len(self.accessories)>0:
            acc.aid = max(self.accessories) + 1
        else:
            acc.aid = 2

**Comment by ikalchev** [comment]
I am actually minutes away from fixing this, thanks.

**Comment by ikalchev** [comment]
The problem was that no matter what the aid is set to by the bridge, it is AFTER the check.

This should be now fixed. Note that AIDS can no longer be set from outside. This will be brought back soon, I wanted to fix this asap. 

Sorry for this fiasco.

FYI: @xtqxk note this change, also affects Http since it is a Bridge.

**Comment by ikalchev** [comment]
Uploaded to PyPi as well. Should be refreshed soon. Try updating with --no-cache-dir if your pip has it.
