### ISSUE TITLE
Suggestion: Dev branch for repo

### ISSUE THREAD

**Issue by cdce8p** [ikalchev/HAP-python#44]
Maybe it could be a good idea to create a `dev` branch for this project.
All PR's would be against the dev branch and later merged with one PR to master.

This would allow for easier maintenance of other projects using `HAP-Python` with the added benefit of a rough change log for each new version in the master branch.

**Comment by ikalchev** [comment]
I am lacking knowledge in this area, but it looks like it could be worth to add it, especially if HAP-python gets integrated into Home Assistant.

**Comment by helmsman35** [comment]
Cdce8p took my experiments and created something in HA, expect the use of HAP-python to explode in the Next few days. I allready responded that the jump he made is way to big for me.

The good thing is that HomeKit support for HA is sped up. 

The bad thing is that at the moment I am not able to contribute anymore due to lack of git knowledge I guess my only contribution is a little experiment to prove things are working and point the HA community to hap-python. 

When I was educated back in the dark ages there was just uncomfortable, mail and newsgroups. We used Modems UUCP and huge telephone bills to call the US to communicate (that is how initial Linux kernel dev was done by our group). No such thing as http, git, forums etc. 

In my line of work there is no such thing as source control as there is nothing public about it. I work in teams, but with other disciplines (electronics, mechanics, Rf engineers and bookkeepers). I was never educated to use source control like git and never got hands-on. Now the communities are so big the whole git thing with all the terms confuse me. I am just beyond the point that I know a fork is not just something to eat with.

I once did published something on git, people started to contribute and I never ever was able to repair the damage that was done to my dev environment other than restore back-ups. So I closed my account finished it for my own use and it is still running today. The community sort of kicked me out, so now they have to live without the stuff I made. 

I tried to get help this time, as I am willing to learn and contribute. This little HA project was started by me as a step up to contribute my machine learning and AI skills into HA and get to know HA, and git. And I feel that exactly that was taken away from me and I am extremely close to what was just published.

**Comment by ikalchev** [comment]
Surely @cdce8p didn't want to just copy your work. I think this will be a lot work and not for a single person. Maybe both of you can discuss the integration and split the work? 

PS: Can we move this discussion to HA community or https://github.com/home-assistant/home-assistant/pull/12488?

**Comment by cdce8p** [comment]
@ikalchev for the moment it would be enough to tag each new release. Makes it way easier to compare changes between release. A good starting point: [stackoverflow](https://stackoverflow.com/questions/18216991/create-a-tag-in-github-repository)

**Comment by helmsman35** [comment]
Cool, I wrote an essay in the other thread about finding information about git/github and here you point to stackoverflow (I love that site). Is It me or should that information be in some GitHub Wiki documentation. The entire GitHub site (and users) just seem to expect people know how it works.

Even Microsoft office has help (ok, not very useful, my experience is not that positive with the Redmond products, and their help always point to the stuff you aren't looking for or makes me feel Microsoft thinks I am stupid goat).

**Comment by helmsman35** [comment]
cool, exactly in the place I was not expecting it, I found this: [https://help.github.com/](https://help.github.com/)

It is on the bottom of I guess every page, hidden behind my laptop screen on my 2nd monitor and in the menu opening when you click on your account avatar in the top right.

**Comment by helmsman35** [comment]
or this: https://git-scm.com/book/en

**Comment by ikalchev** [comment]
Will work on this now, together with #43

**Comment by ikalchev** [comment]
- Created `dev` branch
- Default branch is now `dev`
- Added tag v1.1.7 on `master`
- Merges from `dev` to `master` will come with a new tag, which will be the new version number.
- All new merges to `master` will be uploaded to pypi.

Will work on Travis CI to automate some of this, but this is lower priority now. Tell me if you think the above workflow can be made better.

**Comment by cdce8p** [comment]
Thanks for doing that :+1:
The workflow sounds great and will lead to easier maintenance for other projects that depend on it. As a side note the initial HomeKit support for Home Assistant will be available in the upcoming release. This wouldn't have been possible without your work on `HAP-python`.

On small thing I'm not sure you are doing it already. If you change something, do you commit the changes directly to the `dev` branch or first to a checked out branch which is then merged through a PR?
The later option might seem unnecessary at first, but it would allow others to comment on those changes and might make suggestions. It would also have the added benefit that PR's would work as a change log for the upcoming release.

**Comment by ikalchev** [comment]
Happy to hear the HA integration is going good, thanks!

As for the new commits with PR - sounds good. We have to see if there are enough people commenting as well.
